services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: work-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - /home/nyash/PhpstormProjects/logs/php/First_errors.log:/var/log/php_error.log
  nginx:
    image: nginx:1.29.4
    container_name: work-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./conf/nginx:/etc/nginx/conf.d
    depends_on:
      - app
  db:
    container_name: work-db
    image: mysql:9.5.0
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
volumes:
  mysql_data:
